version = 1

exclude_patterns = [
  "crates/**"
]

[[transformers]]
name = "standardjs"
enabled = true

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "nightly"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]